import type {Metadata} from 'next'
import {Inter, Nunito, Poppins} from 'next/font/google'
import './globals.css'
import {ClerkProvider} from "@clerk/nextjs";
import {Providers} from "@/app/providers";

const poppins = Poppins({
    weight: ["400", "500", "600", "700"],
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <ClerkProvider afterSignInUrl='/' afterSignUpUrl='/'>
            <html lang="en">
            <body className={poppins.className}>
            <Providers>
                {children}
            </Providers>
            </body>
            </html>
        </ClerkProvider>
    )
}
